### ISSUE TITLE
Connecting directly to an instance via direct connect causes an instance crash

### ISSUE THREAD

**Issue by ILLISIS** [Danielv123/gridworld#21]
Connecting directly to an instance via direct connect bypassing the lobby causes an instance crash.

`344.917 Error MainLoop.cpp:1404: Exception at tick 32075: The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_player_joined_game (ID 45)
...on/building_restrictions/set_player_permission_group.lua:12: attempt to index local 'faction' (a nil value)
stack traceback:
	...on/building_restrictions/set_player_permission_group.lua:12: in function 'set_player_permission_group'
	modules/gridworld/gridworld.lua:90: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
 344.917 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_player_joined_game (ID 45)
...on/building_restrictions/set_player_permission_group.lua:12: attempt to index local 'faction' (a nil value)
stack traceback:
	...on/building_restrictions/set_player_permission_group.lua:12: in function 'set_player_permission_group'
	modules/gridworld/gridworld.lua:90: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>"
 344.917 Info ServerMultiplayerManager.cpp:814: updateTick(32075) changing state from(InGame) to(Failed)
 344.932 Info NetworkInputListener.cpp:46: Refusing Input Action [0 65535 ServerCommand] because multiplayer control is not ready
 344.932 Quitting: multiplayer error.
[error] Error handling ipc-inventory_sync_acquire:
Error: Connection closed
    at EventEmitter.onEnd (/home/vm/clusterio/node_modules/rcon-client/lib/rcon.js:113:45)
    at EventEmitter.emit (node:events:530:35)
    at Socket.<anonymous> (/home/vm/clusterio/node_modules/rcon-client/lib/rcon.js:58:26)
    at Socket.emit (node:events:518:28)
    at TCP.<anonymous> (node:net:337:12)
 345.219 Info ServerMultiplayerManager.cpp:154: Quitting multiplayer connection.
 345.220 Info ServerMultiplayerManager.cpp:814: updateTick(4294967295) changing state from(Failed) to(Closed)
 345.221 Info UDPSocket.cpp:233: Closing socket
 345.221 Info UDPSocket.cpp:263: Socket closed
 345.221 Info UDPSocket.cpp:233: Closing socket
 345.316 Info UDPSocket.cpp:233: Closing socket
 345.316 Info UDPSocket.cpp:263: Socket closed
 345.319 Goodbye
[error] Factorio server unexpectedly shut down with code 255`

**Comment by Danielv123** [comment]
Closed through #23

**Comment by Danielv123** [comment]
Ooops wrong issue

**Comment by ILLISIS** [comment]
this looks to be the same as #24
