### ISSUE TITLE
crash on gui click

### ISSUE THREAD

**Issue by ILLISIS** [Danielv123/gridworld#25]
After creating and switch to my own force I was able to join without crashing an instance.. I imagine this is the result but should have a nil check anyway possibly.

`766.830 Error MainLoop.cpp:1404: Exception at tick 45582: The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_gui_click (ID 1)
...les/gridworld/faction/gui/faction_server_status/draw.lua:11: attempt to index local 'player_faction' (a nil value)
stack traceback:
	...les/gridworld/faction/gui/faction_server_status/draw.lua:11: in function 'draw'
	modules/gridworld/gui/menu/events.lua:10: in function '?'
	...urrently-playing/modules/gridworld/util/run_function.lua:3: in function 'run_function'
	modules/gridworld/gui/events.lua:11: in function 'on_gui_click'
	modules/gridworld/gridworld.lua:187: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
 766.831 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_gui_click (ID 1)
...les/gridworld/faction/gui/faction_server_status/draw.lua:11: attempt to index local 'player_faction' (a nil value)
stack traceback:
	...les/gridworld/faction/gui/faction_server_status/draw.lua:11: in function 'draw'
	modules/gridworld/gui/menu/events.lua:10: in function '?'
	...urrently-playing/modules/gridworld/util/run_function.lua:3: in function 'run_function'
	modules/gridworld/gui/events.lua:11: in function 'on_gui_click'
	modules/gridworld/gridworld.lua:187: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>"`

**Comment by ILLISIS** [comment]
After changing to a gridworld precreated faction:


334.934 Error MainLoop.cpp:1404: Exception at tick 55987: The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_gui_click (ID 1)
...les/gridworld/faction/gui/faction_server_status/draw.lua:11: attempt to index local 'player_faction' (a nil value)
stack traceback:
	...les/gridworld/faction/gui/faction_server_status/draw.lua:11: in function 'draw'
	modules/gridworld/gui/menu/events.lua:10: in function '?'
	...urrently-playing/modules/gridworld/util/run_function.lua:3: in function 'run_function'
	modules/gridworld/gui/events.lua:11: in function 'on_gui_click'
	modules/gridworld/gridworld.lua:187: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>
 334.934 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_gui_click (ID 1)
...les/gridworld/faction/gui/faction_server_status/draw.lua:11: attempt to index local 'player_faction' (a nil value)
stack traceback:
	...les/gridworld/faction/gui/faction_server_status/draw.lua:11: in function 'draw'
	modules/gridworld/gui/menu/events.lua:10: in function '?'
	...urrently-playing/modules/gridworld/util/run_function.lua:3: in function 'run_function'
	modules/gridworld/gui/events.lua:11: in function 'on_gui_click'
	modules/gridworld/gridworld.lua:187: in function 'handler'
	__core__/lualib/event_handler.lua:47: in function <__core__/lualib/event_handler.lua:45>"

**Comment by Danielv123** [comment]
How are you joining factions? I thought I disabled the button.

I disabled factions because they aren't updated to alpha 16 yet and they aren't really necessary for what I want to do with it (at least at first) either.

Does these faction bugs happen without joining a faction?

**Comment by ILLISIS** [comment]
Not joining any factions..

simply:
1) create a gridworld
2) join lobby
3) ran into the instance crash
4) swapped forces
